[package]
name = "attachment-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
axum = "0.5.1"
diesel = { version = "1.4.8", features = ["postgres"] }
prost = "0.10.0"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.7.1"

[build-dependencies]
tonic-build = "0.7.0"
