version: "3.9"
services:
  attachment-service:
    build: .
    restart: always
    ports:
      - ${GRPC_PORT}:${GRPC_PORT}
      - ${HTTP_PORT}:${HTTP_PORT}
    volumes:
      - attachment-files:/app/files
    networks:
      - attachments

networks:
  attachments:
