version: "3.9"
services:
  attachment-service:
    build: .
    restart: always
    ports:
      - "50051:50051"
    volumes:
      - attachment-files:/app/files
    networks:
      - attachments

networks:
  attachments:
