version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
    ports:
      - "5132:5432"
    networks:
      - attachments

  attachment-service:
    build: .
    restart: always
    ports:
      - "50051:50051"
    links:
      - postgres
    networks:
      - attachments

networks:
  attachments:
